# Generated by Django 4.2 on 2026-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='programme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
